name: Deploy PowerShell project to Azure Function App

on:
  push:
    branches: ["main"]

env:
  AZURE_FUNCTIONAPP_NAME: mylogicapp7007   # set this to your function app name on Azure
  AZURE_FUNCTIONAPP_PACKAGE_PATH: 'logicapp.zip'       # set this to the path to your function app project, defaults to the repository root

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write #This is required for requesting the JWT
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v4
      - name: zip the logic app
        run: zip -r logicapp.zip . -x ".git/*" ".github/*" "README.md"
        
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.CLIENT_ID }}
          tenant-id: ${{ secrets.TENANT_ID }}
          subscription-id: ${{ secrets.SUB_ID }}
    
      - name: 'Run Azure Functions Action'
        continue-on-error: true
        uses: Azure/functions-action@v1
        id: fa
        with:
          app-name: 'mylogicapp7007'
          # slot-name: 'Production'
          package: logicapp.zip
          # publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}

      - uses: azure/appservice-settings@v1
        with:
          app-name: 'mylogicapp7007'
          app-settings-json: ${{vars.CONFIG}}
        
